# Generated by Django 4.0.3 on 2022-03-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('BURGERS', 'Burgers'), ('SALADS', 'Salads'), ('SNACKS', 'Snacks'), ('POTATOES', 'Potatoes'), ('SOUPS', 'Soups'), ('SAUCES', 'Sauces'), ('BEVERAGES', 'Beverages')], default='burgers', max_length=10, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
