# Generated by Django 4.0.3 on 2022-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='product_photos'),
        ),
    ]
