# Generated by Django 4.0.3 on 2022-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='category_photos'),
        ),
    ]
