# Generated by Django 4.0.3 on 2022-03-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_name_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
